### ISSUE TITLE
Graylog 5.1.2 don't find "Logging Alert Notification " Type 

### ISSUE THREAD

**Issue by yuanfan2012** [airbus-cyber/graylog-plugin-logging-alert#48]
Environment
1、Graylog 5.1.2
2、upload graylog-plugin-logging-alert-5.1.0.jar to  /usr/share/graylog-server/plugin/ 
3、systemctl restart graylog-server

 Alert——New Notification——Notification Type
but I don't find "Logging Alert Notification " Type 
![1](https://github.com/airbus-cyber/graylog-plugin-logging-alert/assets/40062002/a6692d0d-68e3-4916-9131-4234ff2b2b26)
![2](https://github.com/airbus-cyber/graylog-plugin-logging-alert/assets/40062002/9c4a81d1-8867-43cc-9eb3-deece89e8d0c)

**Comment by c8y3** [comment]
It should :)
Sometimes it is only a matter of refreshing the web interface which is cached in the browser.
Could you check the following things:
* check that variable `plugin_dir` in the graylog configuration file `graylog.conf` is `/usr/share/graylog-server/plugin/`. In my case, it is `/usr/share/graylog/plugin` (so that's where I copy the jar).
```
# Set plugin directory here (relative or absolute)
plugin_dir = /usr/share/graylog/plugin
```
* Does graylog loads the plugin at startup? In graylog logs, you should find a line that looks like that:
```
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Logging Alert Notification 5.1.0 [com.airbus-cyber-security.graylog.LoggingAlertPlugin]
```
* Check the plugin is present on the node: in the web interface go to System / Nodes, then click on a node, the list of installed plugins should include a line with `Logging Alert Notification`

As a last resort, you can try the docker-compose that we use for tests. It is present in the source repository. Clone the repository, go into directory `runtime`, create a directory `graylog/plugin`, copy the plugin jar in this directory, then do a `docker-compose up`. Once graylog has started, you should be able to log into http://127.0.0.1:9000/alerts/notifications/new and find the logging notification type.
If this works, from there, you can try to figure out the difference between this and your setup.

Hope this helps. Let us know.
Cheers.

**Comment by yuanfan2012** [comment]
Thanks 
I have checked graylog logs, find a line 
"2023-08-29T15:26:07.201+08:00 ERROR [CmdLineTool] Plugin "Logging Alert Notification" requires version 5.1.3 - not loading!"

so I upgrade graylog-server to 5.1.4 version
the problem solved
the steps :
1、rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-5.1-repository_latest.rpm
2、yum upgrade graylog-server
3、graylog logs:
2023-08-29T15:33:31.155+08:00 INFO  [CmdLineTool] Loaded plugin: Logging Alert Notification 5.1.0 [com.airbus-cyber-security.graylog.LoggingAlertPlugin]
