### ISSUE TITLE
The configuration is not pretty displayed in Graylog v5

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-logging-alert#50]
With Graylog v5.1.4 and Logging Alert v5.1.0 the configuration is not pretty displayed:

![image](https://github.com/airbus-cyber/graylog-plugin-logging-alert/assets/44297634/e2bab404-48b1-458d-9c6e-f4b8a098a33b)

As you can see the name is too long.
I propose to change this ugly long name by "Logging Alert".

**Comment by c8y3** [comment]
The problem is that the name which is displayed is hard-coded inside the graylog2-server interface code-base, rather than brought by the plugin. So graylog2-server must know the plugin before hand.
More precisely, the name which is displayed on the configuration page is the `displayName` (https://github.com/Graylog2/graylog2-server/blob/5.1.3/graylog2-web-interface/src/components/configurations/PluginsConfig.tsx#L93)
To compute the `displayName`graylog searches (https://github.com/Graylog2/graylog2-server/blob/5.1.3/graylog2-web-interface/src/components/configurations/PluginsConfig.tsx#L88) in the table of predefined plugin display names https://github.com/Graylog2/graylog2-server/blob/5.1.3/graylog2-web-interface/src/components/configurations/PluginsConfig.tsx#L45. If it doesn't find it there, it uses the `configType`.
The legacy collector system is present in the table of predefined plugins display names, but not our plugin (obviously) :(
The list of plugins graylog knows is listed here: https://github.com/Graylog2/graylog2-server/blob/5.1.3/graylog2-web-interface/src/components/configurations/ConfigurationTypes.ts#L29

**Comment by frantz45** [comment]
Fixed in Graylog v5.1.10 and v5.2.3.

https://github.com/Graylog2/graylog2-server/issues/15939

**Comment by c8y3** [comment]
This issue has already been raised in issue https://github.com/Graylog2/graylog2-server/issues/15939. It is solved on December 20 by PR https://github.com/Graylog2/graylog2-server/pull/17407.
Unfortunately, it is only present on master https://github.com/Graylog2/graylog2-server/commit/b8bea5c7151cd51bc50340efbdb312d36c771449 and not yet available in either the latest released 5.1 ([5.1.10](https://github.com/Graylog2/graylog2-server/blob/5.1.10/graylog2-web-interface/src/components/configurations/PluginsConfig.tsx)) or the latest released version ([5.2.3](https://github.com/Graylog2/graylog2-server/blob/5.2.3/graylog2-web-interface/src/components/configurations/PluginsConfig.tsx))
Also, see branches [5.1](https://github.com/Graylog2/graylog2-server/commits/5.1) and [5.2](https://github.com/Graylog2/graylog2-server/commits/5.2) histories.

**Comment by frantz45** [comment]
I confirm it's fixed in v6.1.0
